### ISSUE TITLE
Задачи Рефакторинг

### ISSUE THREAD

**Issue by Allyonzy** [ghimik/AlgorythmTheoryLabs#3]
Входные данные к задаче, если мы выносим структуру должны добавляться отдельно от самого кода.
Поправить по принципу "чёрный ящик". Вход вводим (можно с консоли или из файла), получаем информативный вывод (строка приглашения и распечатка словаря).

Для задачи с расстояниями вот это вынести:

``` 
sites = {

        'Moscow': (550, 370),

        'London': (510, 510),

        'Paris': (480, 480),

    }
```

Для остальных задач аналогично.

**Comment by ghimik** [comment]
отрефакторил все
